### ISSUE TITLE
frontend

### ISSUE THREAD

**Issue by chloec2** [CMU-313/fall22-hw3-h1#3]
form frontend

estimated time:

dependencies:

**Comment by MonkeyJerr** [comment]
**Subtask: Displaying the aggregated data on the new dashboard**
Estimated time: Probably around 5 days since it shouldn't be too difficult to display the data once the backend team aggregates it.

Dependencies: Have to wait on backend team to aggregate data, along with middleware team to set up HTTP requests.

Implementation Plan: After the backend team aggregates the data, I will create a new page on Teedy to serve as the new dashboard. Then I'll display the data on the dashboard, with each data field having its own section of the page (average GPA, average SAT score, etc).

How to test:
